### ISSUE TITLE
Use high-level FITSIO interface?

### ISSUE THREAD

**Issue by kbarbary** [emmt/OIFITS.jl#1]
Hi Éric, I just noticed this package. Nice to see that you're developing some Julia code!

I was curious about the reasons why you're not using the high-level FITSIO interface, for, e.g., header manipulation:

``` julia
f = FITS("file.fits")
hdr = readheader(f[1])
hdr["NAXIS1"]  # return the value
getcomment(hdr, "NAXIS1")  # return the comment
```

The header utilities in OIFITS seems really similar.

I'm asking because I'm interested to know the interest in the "low-level" C-style interface versus the "high-level" Julian-style interface as we progress with FITSIO, or any more general feedback on FITSIO.

**Comment by emmt** [comment]
Hi Kyle,

Well, I wanted to quickly figure out how to read the OI-FITS format and 
store it in memory in a Julia session.  My idea was to use your package 
as much as possible and, then, come back to you to see if some of the 
things which were needed can be part of your FITSIO package or can be 
done in a way that makes use of existing methods.

Now that the reading of OI-FITS data is working and tested, I can dare 
bothering you with some remarks:
1. I needed low level access to decode the OI-FITS data which are stored 
   as binary tables in FITS files (I did not see how to do that from the 
   high level interface). I also needed a few low level functions that were 
   not yet part of FITSIO.jl, for instance:
- fits_get_coltype / ffgtdm or ffgtdmll
- fits_get_eqcoltype / ffgtcl or ffgtclll
- fits_read_tdim / ffeqty or ffeqtyll

These could be part of FITSIO.jl, if you like. They are coded in 
https://github.com/emmt/OIFITS.jl/blob/master/src/fix-fitsio.jl
I also implemented only one version the low-level CFITSIO API, because I 
think that the end user want the code to adapt to the type of integers 
that are naturally used by Julia for indexes.
1. I slightly disagree with the way you convert between Julia types and 
   the ones used in CFITSIO. In 
   https://github.com/emmt/OIFITS.jl/blob/master/src/fix-fitsio.jl you have 
   a table of conversions which are more portable (I presume) than e.g. 
   assuming that an `int` in CFITSIO is an `Int32` in Julia.  I agree that 
   this is true for most current machines but may not be true in the future...
2. For the header routine, your high level interface provide most of 
   what I needed but I also wanted means to ensure (and perhaps convert) 
   that the type of a given keyword is correct. I also wanted avoiding to 
   raise errors (well, I realize that I could do that with try/catch 
   statements but I am not really familiar with that).
3. For conversion between CFITSIO type constants, FITS bitpix values and 
   Julia types I extended your _private_ _cfitsio_bitpix() and 
   _cfitsio_datatype() methods (with my understanding of what should be the 
   correspondence as explaines above).

If you agree with some of these, I would be happy to make a 'pull 
request' on FITSIO.jl and remove them form my package. Of course, if you 
have suggestions about simplifying my code I would be happy to implement 
or discuss them ;-)

Eric.

**Comment by kbarbary** [comment]
That all makes perfect sense. Specifics:
1. You're right, there's no Table HDU access in the high-level interface yet, so you certainly had to use the low-level interface for that (TableHDU in the high-level interface is a to-do item for sure.) In the low-level interface, it would be great if you could add your wrappers for `fits_get_coltype`, `fits_get_eqcoltype`, and `fits_read_tdim` to FITSIO.jl. The way you've used either `ffgtdm` or `ffgtdmll` depending on the native Int size seems fine.
2. I haven't looked super close, but I think you're right about the type conversion. Definitely the `int32`s should be `cint`s. All the type conversion stuff could use some cleaning up and I think a PR replacing it with what you have would be welcome. I like your nice comment table giving all the correspondences as well!
3. For the header methods that do type checking and conversion, could you just define methods for the `FITSHeader` type (from FITSIO.jl) in OIFITS? E.g., `oifits_get_real(::FITSHeader, ::ASCIIString)`? And then just use `FITSHeader` everywhere? If you think there are some improvements that can be made to the `FITSHeader` implementation, let me know.

I admit I haven't had a close look at the rest of OIFITS yet. My one surface-level suggestion is that you consider doing away with the `oifits_` prefix on all the methods and then simply not export those methods. When the user does `using OIFITS`, they will be available as, e.g., `OIFITS.get_value()`. It's the same number of characters as `oifits_get_value()` but arguably more Julian. (In fact, FITSIO itself probably exports too many functions and should follow this pattern more.)

Thanks for offering to contribute upstream to FITSIO! It will be great to have your help.

**Comment by emmt** [comment]
Hi Kyle,

Here is the roadmap I propose:
- first, I will fix the types in the ccall's of cfitsio.jl to match the 
  prototypes of functions in fitsio.h (I have already started that but I 
  want to make sure I introduce no mistakes);
- second, I will move the fits_get_coltype, fits_get_eqcoltyp etc. 
  methods form OIFITS.jl to FITSIO.jl
- third, I will follow your suggestions to make OIFITS.jl more Julian 
  and to avoid duplicationg capabilities already in FITSIO.jl

I will issue a pull request after each of the 2 first stages so that you 
can check...

Eric.

Le 13/03/2015 01:57, Kyle Barbary a écrit :

> That all makes perfect sense. Specifics:
> 
>  1.
> 
> ```
> You're right, there's no Table HDU access in the high-level
> interface yet, so you certainly had to use the low-level interface
> for that (TableHDU in the high-level interface is a to-do item for
> sure.) In the low-level interface, it would be great if you could
> add your wrappers for |fits_get_coltype|, |fits_get_eqcoltype|, and
> |fits_read_tdim| to FITSIO.jl. The way you've used either |ffgtdm|
> or |ffgtdmll| depending on the native Int size seems fine.
> ```
> 
>  2.
> 
> ```
> I haven't looked super close, but I think you're right about the
> type conversion. Definitely the |int32|s should be |cint|s. All the
> type conversion stuff could use some cleaning up and I think a PR
> replacing it with what you have would be welcome. I like your nice
> comment table giving all the correspondences as well!
> ```
> 
>  3.
> 
> ```
> For the header methods that do type checking and conversion, could
> you just define methods for the |FITSHeader| type (from FITSIO.jl)
> in OIFITS? E.g., |oifits_get_real(::FITSHeader, ::ASCIIString)|? And
> then just use |FITSHeader| everywhere? If you think there are some
> improvements that can be made to the |FITSHeader| implementation,
> let me know.
> ```
> 
> I admit I haven't had a close look at the rest of OIFITS yet. My one
> surface-level suggestion is that you consider doing away with the
> |oifits_| prefix on all the methods and then simply not export those
> methods. When the user does |using OIFITS|, they will be available as,
> e.g., |OIFITS.get_value()|. It's the same number of characters as
> |oifits_get_value()| but arguably more Julian. (In fact, FITSIO itself
> probably exports too many functions and should follow this pattern more.)
> 
> Thanks for offering to contribute upstream to FITSIO! It will be great
> to have your help.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emmt/OIFITS.jl/issues/1#issuecomment-78724102.

## 

```
                         Eric THIEBAUT
```

  CRAL / Observatoire de Lyon     | eric.thiebaut@univ-lyon1.fr
  9, avenue Charles Andre         | +33-(0)4 78 86 85 48
  F-69561 Saint Genis Laval Cedex | +33-(0)4 78 86 83 86 (fax)
      http://cral.univ-lyon1.fr/labo/perso/eric.thiebaut/

**Comment by kbarbary** [comment]
Sounds perfect!

**Comment by emmt** [comment]
Hi Kyle,

You may have seen the pull request (all tests passed) Now that I have 
read cfitsio.jl in details, I have a few questions and fixes (after the 
--> below) that I would suggest and propose to do:
- mode_strs is not used anywhere
  --> remove it?  Then no more needs for the compat module.
- the value in fits_write_key cannot be Bool
  --> check and fix this
- FITS keyword is sometimes an ASCIIString, sometimes just a String
  --> use ASCIIString everywhere (according to FITS standard)
- conversely some string arguments are not always ASCIIString (the FITS 
  standard stipulates that only ASCII characters are can be used)
  --> use ASCIIString everywhere (according to FITS standard)
- Why not return the coltype in fits_get_col_repeat?
  --> this will done by the fits_get_coltype method
- Why having to specify the type (2nd argument) in fits_read_col and 
  fits_write_col ?  This is redundant with the array element type.
  --> remove this argument and, to avoid breaking old code, provide a 
  (deprecated?) method with this argument and which calls the new one
- Why having to deal with string/non-string type in the body of 
  fits_read_col and fits_write_col ?
  --> make two functions (for each) with different prototypes 
  string/number and rely on Julia dispatcher

Eric

**Comment by kbarbary** [comment]
Thanks for the close review! The code needs it. Responses below...

> mode_strs is not used anywhere

You're right, it can be removed. It was only ever used within `show` but that was rewritten in the high-level interface.

> the value in fits_write_key cannot be Bool

I think we should entirely change the definition of `fits_write_key` to be similar to how `fits_update_key` is defined. That is, we should use the specialized CFITSIO functions `ffpkys`, `ffpkyl`, `ffpkyj` for the different value types. (I never looked too closely at this function because it's not used in the high-level interface.)

> FITS keyword is sometimes an ASCIIString, sometimes just a String

I agree that we should use `ASCIIString` everywhere.

> Why not return the coltype in fits_get_col_repeat?

I'm not sure why this wasn't done; I've never closely inspected any of the table code. You're right that it seems natural to do. We probably shouldn't change the return value in case someone is using it. Instead, we can deprecate the method `fits_get_col_repeat` and define a new method `fits_get_coltype` that returns the coltype as well. This has the added benefit of closely mirroring the CFITSIO function names (which is intended in cfitsio.jl).

> Why having to specify the type (2nd argument) in fits_read_col and
> fits_write_col ?  This is redundant with the array element type.

I agree. I also agree with your solution.

> Why having to deal with string/non-string type in the body of
> fits_read_col and fits_write_col

I agree, and also agree with your solution here.

**Comment by emmt** [comment]
Hi,

According to your advice, I have made the following changes:

> Thanks for the close review! The code needs it. Responses below...
> 
> ```
> mode_strs is not used anywhere
> ```
> 
> You're right, it can be removed. It was only ever used within |show| but
> that was rewritten in the high-level interface.

DONE

> ```
> the value in fits_write_key cannot be Bool
> ```
> 
> I think we should entirely change the definition of |fits_write_key| to
> be similar to how |fits_update_key| is defined. That is, we should use
> the specialized CFITSIO functions |ffpkys|, |ffpkyl|, |ffpkyj| for the
> different value types. (I never looked too closely at this function
> because it's not used in the high-level interface.)

NOT YET DONE (deserve some more thinking)

> ```
> FITS keyword is sometimes an ASCIIString, sometimes just a String
> ```
> 
> I agree that we should use |ASCIIString| everywhere.

DONE

> ```
> Why not return the coltype in fits_get_col_repeat?
> ```
> 
> I'm not sure why this wasn't done; I've never closely inspected any of
> the table code. You're right that it seems natural to do. We probably
> shouldn't change the return value in case someone is using it. Instead,
> we can deprecate the method |fits_get_col_repeat| and define a new
> method |fits_get_coltype| that returns the coltype as well. This has the
> added benefit of closely mirroring the CFITSIO function names (which is
> intended in cfitsio.jl).

DONE: New methods fits_get_coltype, fits_get_eqcoltype and 
fits_read_tdim to to query column format in FITS tables.

> ```
> Why having to specify the type (2nd argument) in fits_read_col and
> fits_write_col ? This is redundant with the array element type.
> ```
> 
> I agree. I also agree with your solution.

DONE

> ```
> Why having to deal with string/non-string type in the body of
> fits_read_col and fits_write_col
> ```
> 
> I agree, and also agree with your solution here.

DONE

**Comment by emmt** [comment]
Hi Kyle,

According to your suggestions, I made lots of change to the OIFITS.jl 
package (removing the oifits_ prefix, using FITSHeader instead of my 
OIHeader, taking into account the now deprecated functions in 
FITSIO.jl). I also made a few changes to FITSIO (see my pending pull 
request) to have methods like readheader, readkey also available at the 
low level interface and to fix a bug in readheader (buffer overflow) 
when dealing with keywords longer than 8 characters (e.g. HIERARCH 
keywords).

There are a few things I would like to have in FITSIO.jl (instead of 
OIFITS.jl) but before I propagate these in my fork of FITSIO.jl I would 
like to have your advice:
- Add a getcomment(hdr::FITSHeader, key::String, def::String) method 
  to return the default result def if key is not present in hdr
- Provide getinteger(hdr::FITSHeader, key::String), getstring(...), 
  getlogical(...), getreal(...), getvalue(...) to retrieve the value of a 
  key in a FITHeader with or without a default value (like for getcomment) 
  and possibly with type checking (the getinteger, getreal getlogical and 
  getstring ones).  Since you already provide a getcomment (with no 
  underscore), I would keep the same semantic for these function. I admit 
  that the getvalue one with no default value is the same as hdr[key] but 
  I would keep it for symmetry...  These functions already exist in 
  https://github.com/emmt/OIFITS.jl/blob/master/src/oifile.jl (but with an 
  underscore) and are very helpful to write clean and concise code with 
  type checking.
- I wrote a readtable method to retrieve the contents of a table in the 
  form of a dictionary, the keys being the column names (in upper case 
  letters and trailing spaces removed) which is available at low level and 
  can be wrapped, at high level, into a read(hdu::TableHDU) method, like 
  the existing high read(hdu::ImageHDU).  The code is in 
  https://github.com/emmt/OIFITS.jl/blob/master/src/misc.jl
- At the low level, we need functions to convert between BITPIX and 
  Julia types and between CFITSIO data type and Julia type, there are 
  currently two functions in FITSIO _cfitsio_bitpix and _cfitsio_datatype 
  but they only do the conversion in one direction (Julia type to integer 
  code) and bitpix_to_type dictionary has to be used to convert BITPIX to 
  Julia type (there is no such counterpart for CFITSIO data type).  I 
  would suggest having a unified interface as:
  
  fits_bitpix(code::Integer) -----> Julia type
  fits_bitpix(T::DataType) -------> BITPIX code
  
  fits_datatype(code::Integer) ---> Julia type
  fits_datatype(T::DataType) -----> CFITSIO type code

plus I see no real reasons to hide these with _cfitsio_ prefixes.  This 
proposed interface is implemented in 
https://github.com/emmt/OIFITS.jl/blob/master/src/fix-fitsio.jl (but you 
already had a look at it).
- Finally, if you agree that I propagate any of these in your FITSIO 
  package, I do I update the doc?

Cheers,

```
Éric.
```

**Comment by kbarbary** [comment]
I agree with most of these.
- `getcomment(hdr::FITSHeader, key::String, def::String)` seems reasonable since it mirrors the behavior of `get()` in the standard library. We can even discuss changing the function to `get_comment`. When I created the function names, I was trying to mirror the standard library (where underscores are not usually used). But I don't have strong feelings about it.
- I would prefer using constructs as `hdr["NAXIS1"]::Int` to do type checking on header values instead of `getinteger`, `getlogical`, etc. It is the typical Julian way to do type checking. If the performance turns out to be an issue (I kinda doubt it...), we can always add a method to `get` that specifies the return type. E.g., `get(hdr, "NAXIS1", Int)`.
- I'll look at your code for reading tables, thanks. I've started working on this myself, as noted in JuliaAstro/FITSIO.jl#27.
- I agree it would be nice to have the symmetry you suggest in `fits_bitpix` and `fits_datatype`. Maybe name the latter `cfitsio_datatype` since is it specific to CFITSIO, whereas the former is part of the the FITS standard?
- Doc updates are always appreciated as parts of PRs (and updating the changelog). Additionally, the docs could use some filling-out. They're incomplete (my fault!).

**Comment by emmt** [comment]
Le 08/04/2015 18:26, Kyle Barbary a écrit :

> I agree with most of these.
> 
>   *
> 
> ```
> |getcomment(hdr::FITSHeader, key::String, def::String)| seems
> reasonable since it mirrors the behavior of |get()| in the standard
> library. We can even discuss changing the function to |get_comment|.
> When I created the function names, I was trying to mirror the
> standard library (where underscores are not usually used). But I
> don't have strong feelings about it.
> ```
> 
>   *
> 
> ```
> I would prefer using constructs as |hdr["NAXIS1"]::Int| to do type
> checking on header values instead of |getinteger|, |getlogical|,
> etc. It is the typical Julian way to do type checking. If the
> performance turns out to be an issue (I kinda doubt it...), we can
> always add a method to |get| that specifies the return type. E.g.,
> |get(hdr, "NAXIS1", Int)|.
> ```
> 
>   *
> 
> ```
> I'll look at your code for reading tables, thanks. I've started
> working on this myself, as noted in JuliaAstro/FITSIO.jl#27
> <https://github.com/JuliaAstro/FITSIO.jl/issues/27>.
> ```
> 
>   *
> 
> ```
> I agree it would be nice to have the symmetry you suggest in
> |fits_bitpix| and |fits_datatype|. Maybe name the latter
> |cfitsio_datatype| since is it specific to CFITSIO, whereas the
> former is part of the the FITS standard?
> ```

OK I have done that in OIFITS.jl/src/fix-fitsio.jl

**Comment by kbarbary** [comment]
One other thing I forgot to mention: one nice thing about Julia is that you can always add methods to a type later, and the methods will still be "first class" (in whatever sense). So you could add methods like `getlogical(::FITSHeader, ::ASCIIString)` within this package, if you still would prefer that.

**Comment by kbarbary** [comment]
I had a look at your revised fix-fitsio.jl and have some questions/comments.
- Why do you define global constants like `TBYTE`, `TSBYTE`, etc? Do you use them elsewhere in OIFITS rather than just using the functions `cfitsio_datatype`, `fits_bitpix`?
- While working on the table interface in FITSIO, I realized that `cfitsio_datatype` is not exactly right for table type `TLONG`. When reading a table, these codes indicate that the storage datatype is a 32-bit Int, so the type should be `Int32` not `Clong`. I'm a little confused though because the cfitsio datatypes `TINT32BIT` and `TLONG` have the same value, even though C long is not always a 32 bit int.

**Comment by emmt** [comment]
You are right for the former: I do not use these constants (and will discard them).

For the latter (data types), I disagree with you but I admit that the doc is rather confusing.  However if you look at the CFITSIO code it confirms what I have assumed in my tables. If you look at functions `ffppx`, `ffppxll` or `ffpcl` (in `putcol.c`) used to write image or table data and at `ffgpxv`, `ffgpxvll` or `ffgcv` (in `getcol.c`) used to read image or table data, you'll see that:

```
TBYTE / TSBYTE ------> unsigned char / signed char
TSHORT / TUSHORT ----> short / unsigned short
TINT / TUINT --------> int / unsigned int
TLONG / TULONG ------> long / unsigned long
TLONGLONG -----------> LONGLONG (64-bit integer in cfistio.h)
TFLOAT --------------> float
TDOUBLE -------------> double
TCOMPLEX ------------> 2*float
TDBLCOMPLEX ---------> 2*double
```

where on the right of the arrows I have put the C-type used in the C code of FITSIO.  I did not do an exhaustive check but the same rules apply in, for instance, the _private_ function `ffpxsz` in `fitscore.c`.

Perhaps you confused with the `I`, `J` and `K` letters used in FITS table to identify 16-, 32- and 64- bit integers?  The letter `K` is a FITS extension supported by CFITSIO, maybe in a specific way.

**Comment by kbarbary** [comment]
Thanks, I think I was confused about the `J` identifier in FITS tables. Well, really my confusion was about going between the format of the data on disk and what cfitsio can read into. For example, the data in some column might be stored as 32-bit int, in which case cfitsio will tell you the data type code is TLONG. But if you use the TLONG code to read it, you won't necessary get a 32-bit int on all platforms. I guess this is unavoidable in cfitsio though.
