### ISSUE TITLE
Won't load 2004 Beauty contest dataset

### ISSUE THREAD

**Issue by fabienbaron** [emmt/OIFITS.jl#4]
The reader won't read the included test files contest-2004-obj1.oifits and  contest-2004-obj2.oifits. Works fine on 2008 contest data. 

Typical error:
reading OI-FITS OI_ARRAY in HDU 2
reading OI-FITS OI_TARGET in HDU 3
reading OI-FITS OI_WAVELENGTH in HDU 4
ERROR: expecting a 2-D array value for field "vis2err" in OI_VIS2
 in error at error.jl:21
 in build_datablock at /home/baron/.julia/v0.3/OIFITS/src/oidata.jl:377
 in read_datablock at /home/baron/.julia/v0.3/OIFITS/src/oifile.jl:212
 in read_datablock at /home/baron/.julia/v0.3/OIFITS/src/oifile.jl:180
 in load at /home/baron/.julia/v0.3/OIFITS/src/oifile.jl:224

**Comment by emmt** [comment]
I will fix that.  However, this bug makes me realize that data fields like `vis2data` are currently returned with the wrong (to me) ordering of dimensions. Indeed, it makes more sense to have the first dimension of such fields used for the time/exposure index (it is the row index in the FITS tables and the row index is the first one in Julia _semantics_).

As shown by the bug you have discovered, it is also more practical to have the number of wavelengths being the second index because for monochromatic data, a column vector of N elements can be seen as a N-by-1 array.

I had made the same choices for the [Yorick interface to OI-FITS](https://github.com/emmt/YOIFITS) for similar reasons.

Changing the ordering of dimensions will however have side effects on existing software (_e.g._ [PAINTER](https://github.com/andferrari/PAINTER.jl)) so I propose to do that in a new branch before merging. In the mean time I will fix the bug without changing dimension ordering.

**Comment by emmt** [comment]
As of commit 84c8c87cebec727bba9e8af824724bba181fc7f3, the bug has been fixed.

The new branch with new dimension ordering is `fix-dims-order`. Make sure to use branch `oi-rev2` if your software is not yet aware of the new dimension ordering. In any cases, old dimension ordering will be obsoleted when writing OI-FITS will be implemented.
